---
- name: Ensure python2 is removed
  package:
    name: python
    state: absent
    autoremove: true

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: true
  when: ansible_os_family | lower == 'debian'
