---
# Tasks for configuring the Vault Agent
- name: Get Vault
  unarchive:
    src: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: /usr/bin
    creates: /usr/bin/vault
    remote_src: True
    validate_certs: True # not required. This only applies if using a https URL as the source of the file. This should only set to C(no) used on personally controlled sites using self-signed certificate. Prior to 2.2 the code worked as if this was set to C(yes).
    mode: 0777
    owner: root
    group: root

- name: Ensure Vault config dir
  file:
    path: /etc/vault/templates
    state: directory
    recurse: True
    mode: 0777
    owner: root
    group: root

- name: Copy vault agent configuration
  copy:
    dest: /etc/vault/vault-agent.hcl
    src:  etc/vault/vault-agent.hcl
    backup: True
    mode: 0444
    directory_mode: True
    owner: root
    group: root

- name: Copy Vault Templates
  copy:
    dest: "/etc/vault/templates/{{ item }}.ctmpl"
    src: "etc/vault/templates/{{ item }}.ctmpl"
    backup: True
    mode: 0444
    directory_mode: True
    owner: root
    group: root
  loop: "{{ vault_templates }}"
